### PR TITLE
macOS: Update packaging and add language translation files.

### PR DESCRIPTION
**Pull request by nobugshere**
PR for issue #1063.  Much of the work is in workflow/macOS-latest.yml and install/macosx/Makefile
* Add background graphics, readme, release notes, and license files to the .dmg package.
* Add help and I18N language translation files.
* Add license files for wx and Yubico libs.
* Update actions in the workflow script to latest versions.
* Update Xcode to 14.2 due to an anomaly in handling languages. (I'm not sure if this could be related to #1039.)
* Remove an old version of create-dmg from the repo and use the current version from Homebrew. (Supports the --eula flag.)

### CODE REVIEW

**Review by ronys — COMMENTED** [review]
Thanks for adding the Yubico and wxWidgets license docs.
I'm not sure that copying the wxWidgets license files is needed or makes sense, though.
Seems more reasonable to me to add a note in the relevant READMEs to the effect that non-Windows versions of PasswordSafe make use of wxWidgets, under the license terms defined in https://wxwidgets.org/about/licence/.

**Comment by nobugshere** [comment]
@ronys, I made the following changes:

- Added your note to README.md about wxWidgets, and some mention of the macOS version :-)
- Removed the wxWidgets folder but kept Yubico because their terms seem to require it.
- Added a rel note for #1009.
- Added .txt extension to the Yubico COPYING* files.

Question: Did you want me to remove the wxWidgets files from the repo, or leave them in the docs folder?

**Comment by nobugshere** [comment]
Attached is a screenshot after the preceding changes:
Screenshot 2023-12-09 at 12 35 46 PM

**Comment by ronys** [comment]
Yes please remove the docs/wxWidgets folder & files.

**Comment by nobugshere** [comment]
> Yes please remove the docs/wxWidgets folder & files.

Done.

**Pull request merged**
