### PR TITLE
Remove word Safe from Lock Safe and Unlock Safe

### PR DESCRIPTION
**Pull request by igor2x**
Remove word "Safe" from "Lock Safe" and "Unlock Safe" strings.

Before this PR for example:
- on Linux File | Lock **Safe**
- on Windows File | Safe

Make wording the same on Windows and non-Windows builds

### CODE REVIEW

**Comment by igor2x** [comment]
@ronys, now I see build for mac-pwsafe failed, but error message is: "Install language files and create dmg"
Did my changes really made this error or is this error from some other source?

**Comment by nobugshere** [comment]
I don't know what happened here.  It looks like the build went okay, then create-dmg created the .dmg disk image, but was not able to unmount it because it was busy for some reason.  All I can suggest is to try it again.  If you go to the Actions tab, in your own repo, and select the mac-pwsafe workflow you should see a button to trigger the workflow on a selected branch.

**Comment by igor2x** [comment]
@nobugshere, on Action tab on my repo it was message that Workflow was disabled in my repo I clicked on enable and now I have empty workflow.
image
This is going to be useful for future build.

**Comment by igor2x** [comment]
I just pushed another simple change and everything has built successfully.
Now PR is ready for review.

**Comment by ronys** [comment]
Re the mac-pwsafe build: I've seen this job fail occasionally on the unmount operation. Looks like a race condition in the build environment. Retrying works for me.

**Pull request merged**
