### PR TITLE
Update Mac build options

### PR DESCRIPTION
**Pull request by nobugshere**
As long as you’re updating the build requirements, I’d like to offer a few Xcode build parameter changes:
- Change the individual target ‘macOS deployment target’ options to use $(inherited).  From then on, the deployment target can be changed in one place at the project level.
- Apply recommended option update from Xcode 14.2: DEAD_CODE_STRIPPING = YES
- Enable the Hardened Runtime.  (A general recommendation on Mac.)
- Add version.wx to the Configs group, just to make it easier to find.

The build artifact runs on my M1 Mac, under Rosetta, with macOS 13.2.1 and a macOS 12 VM.  I have not tested it with older versions of macOS/Xcode or on an Intel Mac.  These are all Xcode changes so I wouldn’t expect them to affect any other platform.  I intend to follow-up with a PR to build a universal executable.

### CODE REVIEW

**Comment by nobugshere** [comment]
The Ubuntu build fails with the same error as PR #932.  Did this just disappear from the Ubuntu repo?
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.81.0-1ubuntu1.8_amd64.deb  404  Not Found [IP: 52.252.75.106 80]

**Comment by nobugshere** [comment]
Well, I can't explain why the Mac build environment worked for @dhocker and not for me but, there is a dylib version of pcre2 in /usr/local/Cellar/pcre2/10.42/lib which my build picked-up.  As a result, the build artifact would fail to find a dynamic version on my Mac.  Removing the *.dylib from that directory allowed pwsafe to be linked with the static version in the same directory.  I don't know why that version of pcre2 is being used (perhaps, left over from wx 3.0?)  So, Instead, I decided to add "--with-regex=builtin" to the wxWidgets configure command to include the version that is pulled along with it.  Now, the build artifact runs properly on my M1 Mac (via Rosetta) and the only dynamic libraries it's using are from /usr/lib.

(Someone else will have to fix Ubuntu 😁)

**Comment by dhocker** [comment]
I probably got the build to work because I "cheated" by modifying the pwsafe-build.xcconfig file. Here's what mine looks like.

BUILD_ROOT = "/Users/dhocker/Source/pwsafe/Xcode/build/Products"
BUILD_DIR = "/Users/dhocker/Source/pwsafe/Xcode/build/Products"

OTHER_LDFLAGS = -L/usr/local/lib -L/Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_osx_cocoau_aui-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_osx_cocoau_xrc-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_osx_cocoau_qa-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_baseu_net-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_osx_cocoau_html-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_osx_cocoau_core-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_baseu_xml-3.1.a /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/libwx_baseu-3.1.a -L/opt/homebrew/Cellar/libtiff/4.3.0/lib -lwxjpeg-3.1 -lwxpng-3.1 -lwxregexu-3.1 -lwxscintilla-3.1 -lexpat -L/opt/homebrew/Cellar/libtiff/4.4.0_1/lib -ltiff -lz -lpthread -liconv -lcurl 
HEADER_SEARCH_PATHS = /Users/dhocker/Source/wxWidgets-3.1.5/static-debug/lib/wx/include/osx_cocoa-unicode-static-3.1 /Users/dhocker/Source/wxWidgets-3.1.5/include

**Comment by nobugshere** [comment]
> I probably got the build to work because I "cheated" by modifying the pwsafe-build.xcconfig file. Here's what mine looks like.

Is that on your own system or in the Github workflow?  Anyway, I do similar things locally but I tried not to change that too much in the PR.  This PR results in the xcconfig file shown below, which doesn't include /usr/local/Cellar.  I think it was being added by the wxWidgets configure script because that's where it found pcre2.  The --with-regex option builds it into the static libs.  I wanted to make sure we have a clean set of libraries because my next PR will be to build a universal executable.  

OTHER_LDFLAGS = -L/usr/local/lib -L/Users/runner/wxbuild/lib /Users/runner/wxbuild/lib/libwx_osx_cocoau_aui-3.2.a /Users/runner/wxbuild/lib/libwx_osx_cocoau_xrc-3.2.a /Users/runner/wxbuild/lib/libwx_osx_cocoau_qa-3.2.a /Users/runner/wxbuild/lib/libwx_baseu_net-3.2.a /Users/runner/wxbuild/lib/libwx_osx_cocoau_html-3.2.a /Users/runner/wxbuild/lib/libwx_osx_cocoau_core-3.2.a /Users/runner/wxbuild/lib/libwx_baseu_xml-3.2.a /Users/runner/wxbuild/lib/libwx_baseu-3.2.a -lwxtiff-3.2 -lwxjpeg-3.2 -lwxpng-3.2 -lwxregexu-3.2 -lwxscintilla-3.2 -lexpat -lz -lpthread -liconv -lcurl 
HEADER_SEARCH_PATHS = /Users/runner/wxbuild/lib/wx/include/osx_cocoa-unicode-static-3.2 /Users/runner/wxbuild/include/wx-3.2

**Comment by nobugshere** [comment]
This PR is superseded by PR #942.  Everything here is included in that PR.

**Pull request closed without merging**
