### PR TITLE
Update pwsafe_de.po

### PR DESCRIPTION
**Pull request by KaiZin2018**
To translate the MacOS specific Menus please please add the changes. May be needed as well for other languages.

### CODE REVIEW

**Comment by ronys** [comment]
I'm a bit confused:
- Where are the referenced texts? What Services, for example?
- Why was this closed? To merge it I need to reopen it. Or was your intent to discard this?

**Comment by KaiZin2018** [comment]
Sorry, this is the first time using git. I hope you can access the changes now.

**Comment by ronys** [comment]
I can access the changes, but I still don't understand them. Can you answer my first question?

**Comment by KaiZin2018** [comment]
Hello,

when running a programm in MacOS X you find some standard menu items beneath File, such as Services, Show All, Hide PasswordSafe, Hide Others or Quit PasswordSafe. These special menu items are Not translated in the moment. I have done for German language, but other languages will need the same.

I can send a screen shot tomorrow, when requested.

Regards 

Kai

**Comment by ronys** [comment]
OK, So I understand that these are somehow implemented by the MacOS X framework.

Thanks for the explanation.

**Pull request merged**
