### PR TITLE
[wx] Redesign of 'CreateShortcutDlg'

### PR DESCRIPTION
**Pull request by rafaelx**

### CODE REVIEW

**Comment by dskrvk** [comment]
Would you mind posting before/after screenshots?

**Comment by rafaelx** [comment]
The current version.
CreateShortcutDialog_current


The redesigned version.
CreateShortcutDialog_redesign

**Comment by dskrvk** [comment]
Thanks, that looks great!

**Comment by rafaelx** [comment]
The current version of 'EditShortcutDlg'.
EditShortcutDialog_current

The redesigned version of 'EditShortcutDlg'.
EditShortcutDialog_redesign

**Comment by ronys** [comment]
One minor comment: The group dropdown should also be editable. In other words, it should be possible to define a new group while creating/editing a shortcut (This is the behavior on Windows).

**Pull request merged**
