### PR TITLE
[wx] Reserve space for Yubi controls to prevent dialog resizing

### PR DESCRIPTION
**Pull request by rafaelx**
Related to #1288, #1245, #1247

### CODE REVIEW

**Comment by nobugshere** [comment]
A *very minor* cosmetic nit-pick: On my Fedora VM, the text gets close to the edge of the window.  

Just for reference, on a newly installed Ubuntu 24.04 VM, the last word wraps and on Mac there is a little space.  Perhaps it's the result of slight differences in font size and shape. 

Fedora 40 ARM64, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42
Fedora Screenshot_2024-06-14_10-12-12

Ubuntu 24.04 ARM64, Gnome/Wayland, gcc 13.2.0, wx 3.2.4, GTK 3.24.41
Ubuntu Screenshot from 2024-06-14 10-23-12

macOS M1Max Sonoma 14.5, Xcode 15.4, wx 3.2.4 (local debug build)
Mac Screenshot 2024-06-14 at 10 14 19 AM

**Comment by nobugshere** [comment]
That last commit doesn't seem to have made any visible difference at all.

**Comment by rafaelx** [comment]
Thanks for testing on different platforms and sharing the results.

It seems that Wx does not respect the spacing requirement for the text element when performing line breaks. Therefore, it is possible that the text comes very close to the edge of the dialog, as shown in the following figure.

PasswordChangeWordWrap

I have increased the height of the available space for the status text so that there is enough space for two lines. The spacing is no longer based on the dialog width, but is limited by the additional panel (visualized by a black border in the screenshot below) on which the status text is placed.

PasswordChangeWordWrapBox

I hope that this will now show the same behavior across all platforms.

**Comment by nobugshere** [comment]
It does look the same on all three platforms now.  The word "button" is initially wrapped to the second line.  When I resize the window, the text reflows as it should.  When shrinking the window, the last word wraps with the right amount of space between it and the edge.  This all looks good to me.  Thanks!

**Pull request merged**
