### PR TITLE
[wx] Disable Autotype controls on Wayland

### LINKED ISSUE #1396: Grey out Perofm Auto Type
I see [PR 1389](https://github.com/pwsafe/pwsafe/pull/1389) was merged. This PR greys out functionalities that do not work. This is great.

I have downloaded today's latest version for Ubuntu from Github Actions. Auto Type does not work on Wayland. May I suggest to grey out Auto Type functions if Wayland is detected.

---
**ISSUE 1**

image

---
**ISSUE 2**

image

---
**ISSUE 3**

image

### PR DESCRIPTION
**Pull request by rafaelx**
Resolves #1396

### CODE REVIEW

**Review by ronys — COMMENTED** [review]
I'm uncomfortable with peppering the code with Wayland-specific stuff.

Something like the following might be better:

wxUtilities::DisableIfUnsupported(enum feature, wxWindow window)
{
 if (feature == Autotype && isWayland)
  {
    window->Disable()
    window->SetToolTip(_("Unsupported on this system");
  }
}

**Comment by ronys** [comment]
Much better - thanks!

**Comment by wohler** [comment]
Did this item first show up in 1.21 on Linux?

I've been running pwsafe under Wayland and autotype has been working just fine with the --nosocket=wayland option.  I just started 1.21 and autotype stopped working and the autotype fields are disabled. I see the tooltip "Not supported by Wayland."

If this is the change that broke autotype for me, can you recommend a workaround, or should I file an issue here or on on flathub/org.pwsafe.pwsafe?

**Comment by wohler** [comment]
Downgrading to 1.20 is one unsatisfactory workaround until this issue is fixed. Thanks.
```
flatpak update --commit=d53c84f5c1e157125e246ab3e4d40da58523272274c61cd299f4431b649d901f org.pwsafe.pwsafe
```

**Pull request merged**
