### PR TITLE
Change dialog's text in create new password database dialog

### PR DESCRIPTION
**Pull request by igor2x**
Fixes [issue 1289](https://github.com/pwsafe/pwsafe/issues/1289).

### CODE REVIEW

**Comment by igor2x** [comment]
image

**Review by ronys — CHANGES_REQUESTED** [review]
The text is grammatically incorrect. Should be "The Master Password will be used to protect the new password database file."  or "The Master Password will be used to protect your new password database file."

As we're getting support requests every few weeks from people who've lost/forgotten their master password, I'm tempted to add a warning text here, but somehow I doubt that it will make a difference. Thoughts?

**Comment by igor2x** [comment]
I have fixed grammar error.

About taking care to not lose the master password warning, I think it should be made a separate PR.
In my humble opinion there should be good idea how to add nice looking warning without getting into text bloating problem again (This PR was done for simplification reasons).

**Comment by igor2x** [comment]
@rony, looking at above errors. Very strange this has fail to build. I just pulled the changes from master repository and merge my fix to it and push. From code alone I can't see any mistake.

I assume:
1. Something was already broken in master branch before I pulled it.
2. For some reason Github build just broke without any reasonable explanation.
3. Something else I don't understand.

How to fix this? Can you pull down the code and make the required changes?

**Comment by nobugshere** [comment]
@igor2x, You tagged "rony" instead of "ronys".  The real @ronys made a commit last night to fix the problem.  It looks like a copy/paste error crept into the master branch before you did your merge.  If you do another merge it should be good.

**Review by ronys — APPROVED** [review]

**Pull request merged**
