### PR TITLE
Update README.LINUX.md

### PR DESCRIPTION
**Pull request by blare-ski**
Updating the CLI installation command for Fedora.

### CODE REVIEW

**Comment by ronys** [comment]
Thanks! Is the dnf command in addition to or instead yum? Perhaps there should be an "or" between the two?

**Comment by blare-ski** [comment]
You're welcome. Also, I don't know. The last update on baseurl.org was in 2011, DistroWatch doesn't track it any more, and in Fedora /bin/yum is a symlink to dnf-3, so... I guess I'd vote for 'instead of,' but I'm a newbie, so.

**Comment by Karneades** [comment]
Yes, Fedora replaced yum with dnf a while back and should be the first choice.

**Comment by Karneades** [comment]
For convenience, you could also add the link to the package in the Fedora section (https://apps.fedoraproject.org/packages/pwsafe).

**Comment by Karneades** [comment]
And looking at pwsafe, this is not the correct passwordsafe ("pwsafe"): https://apps.fedoraproject.org/packages/pwsafe - @blare-ski could you clarify?

**Comment by Karneades** [comment]
Similar topic now also in https://github.com/pwsafe/pwsafe/pull/651.

**Pull request merged**
